networks:
  bookstore-api-network:
    driver: bridge
    ipam:
      driver: default

services:
  bookstore-api-nginx:
    container_name: bookstore-api-nginx
    image: nginx
    ports:
      - '8090:80'
    depends_on:
      - bookstore-api
    volumes:
      - ./src:/var/www
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf
    networks:
      - bookstore-api-network

  bookstore-api:
    container_name: bookstore-api
    build:
      context: docker
      dockerfile: app.Dockerfile
    image: bookstore-api
    ports:
      - '9090:9000'
    volumes:
      - ./src:/var/www
    networks:
      - bookstore-api-network

  bookstore-api-mysql:
    container_name: bookstore-api-mysql
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: bookstore
    ports:
      - '3316:3306'
    volumes:
      - bookstore-api-mysql-volume:/var/lib/mysql
    networks:
      - bookstore-api-network

  bookstore-api-mongo:
    container_name: bookstore-api-mongo
    image: mongo
    ports:
      - 27027:27017
    volumes:
      - ./src:/var/www
      - bookstore-api-mongodb-volume:/data/db
    logging:
      driver: none
    networks:
      - bookstore-api-network

  bookstore-api-node:
    container_name: bookstore-api-node
    build:
      context: docker
      dockerfile: node.Dockerfile
    image: bookstore-api/nodejs
    ports:
      - '5193:5193'
    volumes:
      - ./src:/var/www
    networks:
      - bookstore-api-network

volumes:
  bookstore-api-mysql-volume:
  bookstore-api-mongodb-volume:
